name: ServerListPlus-PlaceholderAPI
main: io.github.jonthesquirrel.serverlistplusplaceholderapi.ServerListPlusPlaceholderAPI
author: [jonthesquirrel]
depend: [ServerListPlus, PlaceholderAPI]
version: ${project.version}
description: Adds a PlaceholderAPI placeholder to ServerListPlus